### PR TITLE
add BUILDING.md and link from root README.md

### LINKED ISSUE #216: Add BUILDING.MD with compilation instructions
Add compilation instructions based on https://gist.github.com/michaelsbradleyjr/989c632ff10df96af328b4263fefac65 and refer them in README.md

It would be nice to see build-from-scratch instructions for other environments too. F.e. now I'm going to compile it with WSL2 Ubuntu, and at least it requires installation of numerous packages

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
Closes #216.

---

TODO: verify all instructions work for
- [x] bare bones Debian (`docker run -it debian`)
- [x] bare bones Fedora (`docker run -it fedora`)
- [x] fresh setup of macOS
- [x] fresh setup of Windows 10 + MSYS2

In future PRs we can make any number of improvements, but this is a solid starting point.

I hope to provide instructions re: getting setup with MSYS2 in a headless Windows container, but I need to spend more time with the [resource](https://github.com/StefanScherer/windows-docker-machine) suggested by dryajov.

### CODE REVIEW

**Comment by michaelsbradleyjr** [comment]
### Context
My host hardware/OS is a 6-Core Intel Core i7 Mac mini running macOS Monterey version 12.5.1.

#### Windows
Using VirtualBox and a current [Microsoft Edge VM image](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), I was able to confirm the instructions in `BUILDING.md` work as expected on a fresh Windows setup.

#### macOS
Using [VMware Fusion](https://www.vmware.com/products/fusion.html), I was able to confirm the instructions in `BUILDING.md` work as expected on a fresh macOS Monterey setup.

**Comment by Bulat-Ziganshin** [comment]
This documentation is a large step forward, allowing strawman to run Codex. For me, it worked on plain Windows and in WSL2.

I request to improve it by adding overview of the entire process. Just now it has Table of Contents, but for strawman it's not obvious what you need to execute it section by section. I think we should include meta-instructions, like "setup your environment by Prerequisites, download as described in Repository and so on".

One possibility is to use Table of Content itself, but switch to numbered sections on top-level and write the instruction as text right here:
```
In order to compile and run Codex, you need to perform the following steps:   // instead of boring "Table of Contents
" header
1. Install developer tools, depending on your platform:
  - Linux
  - ...
2. Download Codex sources
3. Compile executable
4. Optionally, run tests
5. Run Codex executable - link here back to the appropriate README section
```

Alternatively, we can keep current ToC and write this text as a text instruction with links to corresponding BUILDING sections.

**Comment by Bulat-Ziganshin** [comment]
While you are here, please fix also a small mistake in README:

"This will start codex with a data directory pointing to Codex" - it should be "Codex1"

**Comment by michaelsbradleyjr** [comment]
> While you are here, please fix also a small mistake in README...

Fixed.

**Comment by michaelsbradleyjr** [comment]
I have `Run the example` in ToC, `Example usage` as a section heading and in that section link to just above `Example: running two Codex clients` in the main readme.

**Review by Bulat-Ziganshin — APPROVED** [review]
It looks good for me

**Pull request merged**
