### PR TITLE
[marketplace] support latest contracts changes

### PR DESCRIPTION
**Pull request by emizzle**
1. Update the submodule dependency from `dagger-contracts` to `codex-contracts-eth`.
2. The `Storage.sol` contract was removed from `codex-contracts-eth`. This PR supports that change by modifying `nim-codex` accordingly.

### CODE REVIEW

**Review by markspanbroek — APPROVED** [review]
Great! Thanks for picking this up! :pray:

**Comment by emizzle** [comment]
Think it's ok to merge without windows CI passing (and causing the rest to cancel)?

**Comment by markspanbroek** [comment]
> Think it's ok to merge without windows CI passing (and causing the rest to cancel)?

I wouldn't. It's too easy to introduce new errors without a working CI. I'll see whether I can find why the windows CI is failing.

**Comment by markspanbroek** [comment]
Thanks to @Menduist's debugging, the Windows build error was relatively easy to fix: https://github.com/status-im/nimbus-build-system/pull/56. Once that is merged, we can update nimbus build system, and the build error should go away.

**Pull request merged**
