### PR TITLE
Sales REST API

### PR DESCRIPTION
**Pull request by markspanbroek**
Adds a REST API for selling storage

- Adds integration tests that starts a couple of nodes, and interacts with them via the REST API.
- Fixes a version conflict in the nimble file
- Removes obsolete ASDF version file

### CODE REVIEW

**Comment by Menduist** [comment]
make libbacktrace

Before trying to compile anything :)

**Comment by markspanbroek** [comment]
> make libbacktrace
> 
> Before trying to compile anything :)

Thanks for the tip!

**Review by dryajov — APPROVED** [review]
I think this can be rebased and merged... the conflicts are minor.

**Comment by markspanbroek** [comment]
I'll finish off #92, and then rebase both.

**Pull request merged**
